export const tabsData = [
  {
    id: "SY-DI",
    label: "دمشق",
    cards: [
      {
        link: "#",
        speed: "50 Mbps",
        unlimited: "غير محدود",
        offerDuration: "3 أشهر",
        city: "دمشق",
        price: "500 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "100 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "دمشق",
        price: "800 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "100 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "دمشق",
        price: "800 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "100 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "دمشق",
        price: "800 TL",
        buttonText: "اشترك الآن",
      },
    ],
  },
  {
    id: "SY-RD",
    label: "ريف دمشق",
    cards: [
      {
        link: "#",
        speed: "50 Mbps",
        unlimited: "غير محدود",
        offerDuration: "3 أشهر",
        city: "دمشق",
        price: "500 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "100 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "دمشق",
        price: "800 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "100 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "دمشق",
        price: "800 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "100 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "دمشق",
        price: "800 TL",
        buttonText: "اشترك الآن",
      },
    ],
  },
  {
    id: "SY-HL",
    label: "حلب",
    cards: [
      {
        link: "#",
        speed: "40 Mbps",
        unlimited: "غير محدود",
        offerDuration: "3 أشهر",
        city: "حلب",
        price: "450 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "80 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "حلب",
        price: "750 TL",
        buttonText: "اشترك الآن",
      },
    ],
  },
  {
    id: "SY-LA",
    label: "اللاذقية",
    cards: [
      {
        link: "#",
        speed: "60 Mbps",
        unlimited: "غير محدود",
        offerDuration: "3 أشهر",
        city: "اللاذقية",
        price: "480 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "120 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "اللاذقية",
        price: "900 TL",
        buttonText: "اشترك الآن",
      },
    ],
  },
  {
    id: "SY-HI",
    label: "حمص",
    cards: [
      {
        link: "#",
        speed: "50 Mbps",
        unlimited: "غير محدود",
        offerDuration: "3 أشهر",
        city: "حمص",
        price: "470 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "90 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "حمص",
        price: "820 TL",
        buttonText: "اشترك الآن",
      },
    ],
  },
  {
    id: "SY-HM",
    label: "حماة",
    cards: [
      {
        link: "#",
        speed: "40 Mbps",
        unlimited: "غير محدود",
        offerDuration: "3 أشهر",
        city: "حماة",
        price: "450 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "80 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "حماة",
        price: "780 TL",
        buttonText: "اشترك الآن",
      },
    ],
  },
  {
    id: "SY-T",
    label: "طرطوس",
    cards: [
      {
        link: "#",
        speed: "60 Mbps",
        unlimited: "غير محدود",
        offerDuration: "3 أشهر",
        city: "طرطوس",
        price: "500 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "100 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "طرطوس",
        price: "850 TL",
        buttonText: "اشترك الآن",
      },
    ],
  },
  {
    id: "SY-ID",
    label: "إدلب",
    cards: [
      {
        link: "#",
        speed: "30 Mbps",
        unlimited: "غير محدود",
        offerDuration: "3 أشهر",
        city: "إدلب",
        price: "420 TL",
        buttonText: "اشترك الآن",
      },
      {
        link: "#",
        speed: "70 Mbps",
        unlimited: "غير محدود",
        offerDuration: "6 أشهر",
        city: "إدلب",
        price: "750 TL",
        buttonText: "اشترك الآن",
      },
    ],
  },
];